server:
  port: 8004

spring:
  application:
    name: bcy-cloud-feign

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://47.115.128.193:8000/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

#日志
logging:
  file:
    path: /spring/log
    name: bcy-feign.log

ribbon:
  #建立连接后从服务器读到可用资源时间限制（空是显示bug）
  RedTimeout: 20000
  #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用时间限制
  ConnectTimeout: 20000


