server:
  port: 8003

spring:
  datasource:
    username: mycat
    password: 123456
    url: jdbc:mysql://47.115.128.193:8066/mycatdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: bcy-cloud-hystrix-acgpart
  #rabbitmq
  rabbitmq:
    host: 47.115.128.193
    port: 5672
    username: ck
    password: 123456
    virtual-host: /
  #redis
  redis:
    host: 47.115.128.193
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  profiles:
    #开发者环境
    active: dev



eureka:
  instance:
    #用ip代替实例名
    prefer-ip-address: true
    #实例的主机名
    hostname: 1.117.75.49
    #实例的ID规则
    instance-id: 1.117.75.49:${spring.application.name}:${server.port}
    #设置ip
    ip-address: 1.117.75.49
  client:
    #不是注册中心都是true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://47.115.128.193:8000/eureka