server:
  #使用https默认端口
  port: 443
  ssl:
    #证书路径
    key-store: classpath:rat403.cn.pfx
    #证书密码
    key-store-password: N2sjS3S3
    #证书类型
    key-store-type: PKCS12
    #开启ssl
    enabled: true

spring:
  application:
    name: bcy-cloud-gateway
  cloud:
    gateway:
      routes:
          #路由ID，唯一
        - id: userpart_routh
          #匹配后提供服务的路由地址
          uri: http://47.115.128.193:8004
          predicates:
            #userpart发给consumer
            - Path=/user/**
        - id: community_routh
          uri: http://47.115.128.193:8004
          predicates:
            - Path=/community/**
        - id: acgpart_routh
          uri: http://47.115.128.193:8004
          predicates:
            - Path=/acg/**
        - id: websocket_routh
          uri: ws://47.115.128.193:8004


eureka:
  instance:
    #服务网关注册名
    hostname: bcy-cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://47.115.128.193:8000/eureka